@FamilyShoppingList_HostAddress = http://localhost:5250

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE2YTE2NDBlLTIxODMtNGZhNi04YzFkLTM1OTEwMmZkYWFlYiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJ5b3Vzc2VmMzMiLCJleHAiOjE3ODYyMTMwMDMsImlzcyI6IkZhbWlseVNob3BwaW5nTGlzdCIsImF1ZCI6IkZhbWlseVNob3BwaW5nTGlzdCJ9.koT1Vy3PCEVfS5r1sYCHror6uilMkXWGY8QyQibJuGc

###
POST https://sharedshoppinglist-angbafbghgh5huef.uaenorth-01.azurewebsites.net/register
Content-Type: application/json

{
  "username": "usertest1",
  "email": "usertest1@gmail.com",
  "Password": "A23123123"
}
###
POST {{FamilyShoppingList_HostAddress}}/register
Content-Type: application/json

{
  "username": "usertest1",
  "email": "usertest1@gmail.com",
  "Password": "A23123123"
}

###
POST {{FamilyShoppingList_HostAddress}}/login
Content-Type: application/json

{
  "Username": "usertest1",
  "Password": "A23123123"
}

###
POST {{FamilyShoppingList_HostAddress}}/refresh
Content-Type: application/json


###
POST {{FamilyShoppingList_HostAddress}}/groups
Authorization: Bearer {{authToken}}
Content-Type: application/json
{
  "name": "test group 2 33"
}

###
GET {{FamilyShoppingList_HostAddress}}/groups/f81f4f2c-ded9-42f0-aca9-360e3b484076/members
Authorization: Bearer {{authToken}}
Content-Type: application/json

###
GET {{FamilyShoppingList_HostAddress}}/groups
Authorization: Bearer {{authToken}}
Content-Type: application/json
